query GetDocumentVersion($objectKey: ID!, $runId: String!) {
  getDocumentVersion(objectKey: $objectKey, runId: $runId) {
    RunId
    ObjectKey
    CompletionTime
    QueuedTime
    WorkflowStartTime
    WorkflowExecutionArn
    ConfigVersion
    ConfigRevision
    PageCount
    FileCount
    ManifestUri
    SummaryReportUri
    EvaluationReportUri
    Metering
    Sections {
      Id
      PageIds
      Class
      Confidence
      OutputJSONUri
      InstanceCount
      Excluded
      ExclusionReason
      ConfidenceThresholdAlerts {
        attributeName
        confidence
        confidenceThreshold
      }
      ProcessingIssues {
        stage
        severity
        code
        message
        rootCause
      }
    }
    Pages {
      Id
      Class
      ClassConfidence
      ClassReason
      ClassCandidates {
        Class
        Probability
      }
      ImageUri
      TextUri
      OcrPageDataUri
    }
    Files {
      Key
      VersionId
      Size
    }
  }
}
