# Document Classes and Attributes Configuration
classes:
  - name: Bank Statement
    description: Monthly bank account statement
    attributes:
      - name: Account Number
        description: Primary account identifier
        attributeType: simple
        evaluation_method: EXACT
      - name: Statement Period
        description: Statement period (e.g., January 2024)
        evaluation_threshold: '0.8'
        attributeType: simple
        evaluation_method: FUZZY
      - name: Account Holder Address
        description: Complete address information for the account holder
        attributeType: group
        groupAttributes:
          - name: Street Number
            description: House or building number
            evaluation_threshold: '0.9'
            evaluation_method: FUZZY
          - name: Street Name
            description: Name of the street
            evaluation_threshold: '0.8'
            evaluation_method: FUZZY
          - name: City
            description: City name
            evaluation_threshold: '0.9'
            evaluation_method: FUZZY
          - name: State
            description: State abbreviation (e.g., CA, NY)
            evaluation_method: EXACT
          - name: ZIP Code
            description: 5 or 9 digit postal code
            evaluation_method: EXACT
      - name: Transactions
        listItemTemplate:
          itemAttributes:
            - name: Date
              description: Transaction date (MM/DD/YYYY)
              evaluation_threshold: '0.9'
              evaluation_method: FUZZY
            - name: Description
              description: Transaction description or merchant name
              evaluation_threshold: '0.7'
              evaluation_method: SEMANTIC
            - name: Amount
              description: >-
                Transaction amount (positive for deposits, negative for
                withdrawals)
              evaluation_method: NUMERIC_EXACT
          itemDescription: Individual transaction record
        description: List of all transactions in the statement period
        attributeType: list