// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import type { aws_appsync } from 'aws-cdk-lib';

/**
 * Properties for a GraphQL API that has a predefined schema
 */
export interface ProcessingEnvironmentApiBaseProps {
  /**
   * A flag indicating whether or not X-Ray tracing is enabled for the GraphQL API.
   * @default - false
   * @stability stable
   */
  readonly xrayEnabled?: boolean;
  /**
   * A value indicating whether the API is accessible from anywhere (GLOBAL) or can only be access from a VPC (PRIVATE).
   * @default - GLOBAL
   * @stability stable
   */
  readonly visibility?: aws_appsync.Visibility;
  /**
   * A number indicating the maximum number of resolvers that should be accepted when handling queries.
   * Value must be withing range of 0 to 10000
   * @default - The default value is 0 (or unspecified), which will set the limit to 10000
   * @stability stable
   */
  readonly resolverCountLimit?: number;
  /**
   * A number indicating the maximum depth resolvers should be accepted when handling queries.
   * Value must be withing range of 0 to 75
   * @default - The default value is 0 (or unspecified) which indicates no maximum depth.
   * @stability stable
   */
  readonly queryDepthLimit?: number;
  /**
   * The owner contact information for an API resource.
   * This field accepts any string input with a length of 0 - 256 characters.
   * @default - No owner contact.
   * @stability stable
   */
  readonly ownerContact?: string;
  /**
   * Logging configuration for this api.
   * @default - None
   * @stability stable
   */
  readonly logConfig?: aws_appsync.LogConfig;
  /**
   * A value indicating whether the API to enable (ENABLED) or disable (DISABLED) introspection.
   * @default IntrospectionConfig.ENABLED
   * @stability stable
   */
  readonly introspectionConfig?: aws_appsync.IntrospectionConfig;
  /**
   * A map containing the list of resources with their properties and environment variables.
   * There are a few rules you must follow when creating keys and values:
   *   - Keys must begin with a letter.
   *   - Keys must be between 2 and 64 characters long.
   *   - Keys can only contain letters, numbers, and the underscore character (_).
   *   - Values can be up to 512 characters long.
   *   - You can configure up to 50 key-value pairs in a GraphQL API.
   * @default - No environment variables.
   * @stability stable
   */
  readonly environmentVariables?: Record<string, string>;
  /**
   * The domain name configuration for the GraphQL API.
   * The Route 53 hosted zone and CName DNS record must be configured in addition to this setting to
   * enable custom domain URL
   * @default - no domain name
   * @stability stable
   */
  readonly domainName?: aws_appsync.DomainOptions;
  /**
   * Optional authorization configuration.
   * @default - API Key authorization
   * @stability stable
   */
  readonly authorizationConfig?: aws_appsync.AuthorizationConfig;
  /**
   * the name of the GraphQL API.
   * @stability stable
   */
  readonly name?: string;
}
