/*
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/

import * as path from "path";
import * as cdk from "aws-cdk-lib";
import * as appsync from "aws-cdk-lib/aws-appsync";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as kms from "aws-cdk-lib/aws-kms";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as logs from "aws-cdk-lib/aws-logs";
import { IBucket } from "aws-cdk-lib/aws-s3";
import { Construct } from "constructs";
import { LogLevel } from "../log-level";
import { ProcessingEnvironmentApiBaseProps } from "./processing-environment-api-base-props";
import { IConfigurationTable } from "../configuration-table";
import { ITrackingTable } from "../tracking-table";
import { VpcConfiguration } from "../vpc-configuration";
import * as functions from "./functions";

/**
 * Interface for features that can be enabled in the ProcessingEnvironmentApi.
 *
 * This interface enables a plugin architecture where features encapsulate their own
 * integration logic rather than having the API manage all feature integrations.
 * Features implementing this interface can create their own data sources and resolvers
 * by calling helper methods on the API.
 *
 * Example:
 * class MyFeature extends Construct implements IApiFeature {
 *   public enableInApi(api: IProcessingEnvironmentApi): void {
 *     const dataSource = api.addLambdaDataSource('MyFeatureDataSource', this.myFunction);
 *     dataSource.createResolver('MyFeatureResolver', {
 *       typeName: 'Query',
 *       fieldName: 'myFeature',
 *     });
 *   }
 * }
 *
 */
export interface IApiFeature {
  /**
   * Enable this feature in the ProcessingEnvironmentApi.
   *
   * Typically adds GraphQL resolvers, data sources, and Lambda functions.
   * This method is called by the feature to integrate itself with the API.
   *
   * @param api The ProcessingEnvironmentApi to enable in
   */
  enableInApi(api: IProcessingEnvironmentApi): void;
}

/**
 * Interface for the document processing environment API.
 * Provides GraphQL API capabilities for monitoring and managing document processing.
 */
export interface IProcessingEnvironmentApi extends appsync.IGraphqlApi {
  /**
   * The URL endpoint for the GraphQL API.
   * Used by client applications to interact with the document processing system.
   */
  readonly graphqlUrl: string;

  /**
   * The Lambda function that generates presigned URLs for document uploads.
   * Features that need to support uploads to additional buckets can grant
   * this function write access and add environment variables.
   */
  readonly uploadResolverFunction: lambda.IFunction;

  /**
   * Enable a feature in the ProcessingEnvironmentApi.
   *
   * This is the recommended way to integrate features with the API.
   * Features implementing IApiFeature will enable themselves
   * in the API by creating data sources and resolvers.
   *
   * @example
   * const agentAnalytics = new AgentAnalytics(this, 'AgentAnalytics', { ... });
   * api.enable(agentAnalytics);
   *
   * @param feature The feature to enable in the API
   *    */
  enable(feature: IApiFeature): void;
}

/**
 * Properties for configuring the ProcessingEnvironmentApi construct.
 * Extends the base properties with additional settings specific to document processing.
 */
export interface ProcessingEnvironmentApiProps extends ProcessingEnvironmentApiBaseProps {
  /**
   * The S3 bucket where source documents to be processed are stored.
   * This bucket is monitored for new document uploads to trigger processing.
   */
  readonly inputBucket: IBucket;

  /**
   * The S3 bucket where processed documents and extraction results are stored.
   * Contains the structured data output and processing artifacts.
   */
  readonly outputBucket: IBucket;

  /**
   * The DynamoDB table that tracks document processing status and metadata.
   * Stores information about documents being processed, including status and results.
   */
  readonly trackingTable: ITrackingTable;

  /**
   * The DynamoDB table that stores configuration settings.
   * Contains document schemas, extraction parameters, and other system-wide settings.
   */
  readonly configurationTable: IConfigurationTable;

  /**
   * Optional KMS key used for encrypting sensitive data in the processing environment.
   * When provided, ensures that document content and metadata are encrypted at rest.
   */
  readonly encryptionKey?: kms.IKey;

  /**
   * The retention period for CloudWatch logs generated by document processing components.
   * Controls how long system logs are kept for troubleshooting and auditing.
   */
  readonly logRetention?: logs.RetentionDays;

  /**
   * The log level for document processing components.
   * Controls the verbosity of logs generated during document processing.
   */
  readonly logLevel?: LogLevel;

  /**
   * Optional VPC configuration for document processing components.
   * When provided, deploys processing components within a VPC with specified settings.
   */
  readonly vpcConfiguration?: VpcConfiguration;

  /**
   * Optional users table for RBAC-based document filtering.
   * When provided, the GSI-based listDocuments resolver checks user's
   * allowedConfigVersions to scope document visibility per user role.
   *
   * @default - No RBAC filtering by config version
   * @since 0.5.2
   */
  readonly usersTable?: dynamodb.ITable;
}

/**
 * A construct that provides a GraphQL API for tracking and managing document processing.
 *
 * The ProcessingEnvironmentApi creates an AppSync GraphQL API with resolvers for:
 * - Querying document status and metadata
 * - Managing document processing (delete, reprocess)
 * - Accessing document contents and extraction results
 * - Uploading new documents for processing
 * - Copying documents to baseline for evaluation
 *
 * Additional features can be integrated using the `enable()` method, which
 * accepts any construct implementing `IApiFeature`.
 *
 */
export class ProcessingEnvironmentApi
  extends appsync.GraphqlApi
  implements IProcessingEnvironmentApi
{
  /**
   * The Lambda function that generates presigned URLs for document uploads.
   */
  public readonly uploadResolverFunction: lambda.IFunction;

  private readonly _encryptionKey?: kms.IKey;
  private readonly _logRetention?: logs.RetentionDays;
  private readonly _vpcConfiguration?: VpcConfiguration;
  private readonly _trackingTable: ITrackingTable;
  private readonly _usersTable?: dynamodb.ITable;

  /**
   * Creates a new ProcessingEnvironmentApi.
   *
   * @param scope The construct scope
   * @param id The construct ID
   * @param props Configuration properties for the API
   */
  constructor(
    scope: Construct,
    id: string,
    props: ProcessingEnvironmentApiProps,
  ) {
    super(scope, id, {
      ...props,
      name:
        props.name ||
        cdk.Lazy.string({
          produce: () => cdk.Names.uniqueResourceName(this, { maxLength: 128 }),
        }),
      definition: appsync.Definition.fromFile(
        path.join(
          __dirname,
          "..",
          "..",
          "assets",
          "appsync",
          "env-api",
          "schema.graphql",
        ),
      ),
    });

    // Store configuration for later use in add* methods
    this._encryptionKey = props.encryptionKey;
    this._logRetention = props.logRetention;
    this._vpcConfiguration = props.vpcConfiguration;
    this._trackingTable = props.trackingTable;
    this._usersTable = props.usersTable;

    // Add file contents resolver
    const getFileContentsDataSource = this.addGetFileContentsDataSource(
      props.inputBucket,
      props.outputBucket,
      props.encryptionKey,
      props.vpcConfiguration,
    );
    this.createGetFileContentsQueryResolver(getFileContentsDataSource);

    // Add document upload and reprocess resolvers
    const uploadDocumentDataSource = this.addUploadDocumentDataSource(
      props.inputBucket,
      props.outputBucket,
      props.encryptionKey,
      props.logRetention,
      props.vpcConfiguration,
    );
    this.createUploadDocumentMutationResolver(
      uploadDocumentDataSource.dataSource,
    );
    this.uploadResolverFunction = uploadDocumentDataSource.resolverFunction;

    const reprocessDocumentDataSource = this.addReprocessDocumentDataSource(
      props.inputBucket,
      props.encryptionKey,
      props.logRetention,
      props.vpcConfiguration,
    );

    this.createReprocessDocumentMutationResolver(reprocessDocumentDataSource);

    // Add core functionality
    this.addTrackingTable(
      props.trackingTable,
      props.inputBucket,
      props.outputBucket,
    );
    this.addConfigurationTable(props.configurationTable);
  }

  /**
   * Add a Lambda data source to the GraphQL API.
   *
   * This helper method allows features to register their Lambda functions as data sources
   * for GraphQL resolvers. Features implementing IApiAttachable can use this method
   * during their attachTo() implementation to create data sources.
   *
   * @param id The unique identifier for the data source
   * @param fn The Lambda function to use as the data source
   * @param options Optional configuration for the data source
   * @returns The created Lambda data source
   *    */
  public addLambdaDataSource(
    id: string,
    fn: lambda.IFunction,
    options?: appsync.DataSourceOptions,
  ): appsync.LambdaDataSource {
    return super.addLambdaDataSource(id, fn, options);
  }

  /**
   * Add a None data source to the GraphQL API.
   *
   * This helper method allows features to create None data sources for resolvers
   * that don't require a backend (e.g., for local resolvers or pass-through operations).
   * Features implementing IApiFeature can use this method during their enableInApi()
   * implementation.
   *
   * @param id The unique identifier for the data source
   * @param options Optional configuration for the data source
   * @returns The created None data source
   *    */
  public addNoneDataSource(
    id: string,
    options?: appsync.DataSourceOptions,
  ): appsync.NoneDataSource {
    return super.addNoneDataSource(id, options);
  }

  /**
   * Enable a feature in the ProcessingEnvironmentApi.
   *
   * This is the recommended way to integrate features with the API.
   * The feature will enable itself in the API by creating data sources and resolvers.
   *
   * @example
   * const agentAnalytics = new AgentAnalytics(this, 'AgentAnalytics', { ... });
   * api.enable(agentAnalytics);
   *
   * @param feature The feature to enable in the API
   *    */
  public enable(feature: IApiFeature): void {
    feature.enableInApi(this);
  }

  /**
   * Add tracking table data sources and resolvers to the GraphQL API.
   *
   * This method adds all tracking table related functionality including:
   * - Document creation and management
   * - Document status tracking
   * - Document listing and querying
   * - Document metadata management
   * - Document deletion (from tracking table and S3 buckets)
   *
   * @example
   * // Add tracking table functionality after API creation
   * api.addTrackingTable(myTrackingTable, inputBucket, outputBucket);
   *
   * @param trackingTable The DynamoDB table that tracks document processing status and metadata
   * @param inputBucket The S3 bucket where source documents are stored
   * @param outputBucket The S3 bucket where processed documents are stored
   */
  public addTrackingTable(
    trackingTable: ITrackingTable,
    inputBucket: IBucket,
    outputBucket: IBucket,
  ): void {
    // Add delete document functionality (depends on tracking table)
    const deleteDocumentDataSource = this.addDeleteDocumentDataSource(
      trackingTable,
      inputBucket,
      outputBucket,
      this._encryptionKey,
      this._logRetention,
      this._vpcConfiguration,
    );
    this.createDeleteDocumentMutationResolver(deleteDocumentDataSource);

    // Add core tracking table functionality
    this.addTrackingTableDataSourceAndResolvers(trackingTable);
  }

  /**
   * Add configuration table data sources and resolvers to the GraphQL API.
   *
   * This method adds configuration management functionality including:
   * - Querying configuration settings
   * - Updating configuration parameters
   * - Managing document schemas and extraction parameters
   *
   * @example
   * // Add configuration table functionality after API creation
   * api.addConfigurationTable(myConfigurationTable);
   *
   * @param configurationTable The DynamoDB table that stores configuration settings
   */
  public addConfigurationTable(configurationTable: IConfigurationTable): void {
    this.addConfigurationResolver(
      configurationTable,
      this._encryptionKey,
      this._logRetention,
      this._vpcConfiguration,
    );
  }

  private addTrackingTableDataSourceAndResolvers(
    trackingTable: ITrackingTable,
  ) {
    const trackingTableDataSource = this.addDynamoDbDataSource(
      "TrackingTableDataSource",
      trackingTable,
    );

    // Create the createDocument resolver
    trackingTableDataSource.createResolver("CreateDocumentResolver", {
      typeName: "Mutation",
      fieldName: "createDocument",
      requestMappingTemplate: appsync.MappingTemplate.fromString(`
          #set( $PK = "doc#\${ctx.args.input.ObjectKey}" )
  
          #set( $shardsInDay = 6 )
          #set( $shardDivider = 24 / $shardsInDay )
          #set( $Integer = 0 )
          #set( $now = $ctx.args.input.QueuedTime )
          #set( $date = $now.substring(0, 10) )
          #set( $hourString = $now.substring(11, 13) )
          #set( $hour = $Integer.parseInt($hourString) )
          #set( $hourShard = $hour / $shardDivider )
          #set( $shardPad = $date.format("%02d", $hourShard) )
          #set( $listPk = "list#\${date}#s#\${shardPad}" )
          #set( $listSk = "ts#\${now}#id#\${ctx.args.input.ObjectKey}" )
  
          {
            "version" : "2018-05-29",
            "operation" : "TransactWriteItems",
            "transactItems": [
              {
                "table": "${trackingTable.tableName}",
                "operation": "PutItem",
                "key" : {
                  "PK": $util.dynamodb.toDynamoDBJson($PK),
                  "SK": $util.dynamodb.toDynamoDBJson("none"),
                },
                "attributeValues": $util.dynamodb.toMapValuesJson($ctx.args.input),
              },
              {
                "table": "${trackingTable.tableName}",
                "operation": "PutItem",
                "key" : {
                  "PK": $util.dynamodb.toDynamoDBJson($listPk),
                  "SK": $util.dynamodb.toDynamoDBJson($listSk),
                },
                "attributeValues": {
                  "ObjectKey": $util.dynamodb.toDynamoDBJson($ctx.args.input.ObjectKey),
                  "QueuedTime": $util.dynamodb.toDynamoDBJson($ctx.args.input.QueuedTime),
                  "ExpiresAfter": $util.dynamodb.toDynamoDBJson($ctx.args.input.ExpiresAfter),
                },
              },
            ],
          }`),
      responseMappingTemplate: appsync.MappingTemplate.fromString(`
          #if($ctx.error)
            $util.error($ctx.error.message, $ctx.error.type)
          #end
          $util.toJson({"ObjectKey": $ctx.args.input.ObjectKey})`),
    });

    trackingTableDataSource.createResolver("UpdateDocumentResolver", {
      typeName: "Mutation",
      fieldName: "updateDocument",
      requestMappingTemplate: appsync.MappingTemplate.fromString(`
        #set( $PK = "doc#\${ctx.args.input.ObjectKey}" )
        #set( $expNames = {} )
        #set( $expValues = {} )
        #set( $expSet = {} )
        ## Iterate through each argument with values and update expression variables **
        #foreach( $entry in $ctx.args.input.entrySet() )
            ## skip empty values **
            #if( !$util.isNullOrBlank($entry.value)  )
                $util.qr( $expSet.put("#\${entry.key}", ":\${entry.key}") )
                $util.qr( $expNames.put("#\${entry.key}", "\${entry.key}") )
                $util.qr( $expValues.put(":\${entry.key}", $util.dynamodb.toDynamoDB($entry.value)) )
            #end
        #end
        ## Start building the update expression, starting with attributes we're going to SET **
        #set( $expression = "" )
        #if( !$\{expSet.isEmpty()} )
            #set( $expression = "SET" )
            #foreach( $entry in $expSet.entrySet() )
                #set( $expression = "\${expression} \${entry.key} = \${entry.value}" )
                #if ( $foreach.hasNext )
                    #set( $expression = "\${expression}," )
                #end
            #end
        #end
        {
            "version" : "2018-05-29",
            "operation" : "UpdateItem",
            "key" : {
              "PK": $util.dynamodb.toDynamoDBJson($PK),
              "SK": $util.dynamodb.toDynamoDBJson("none"),
            },
            "update" : {
                "expression": "$expression"
                #if( !$\{expNames.isEmpty()} )
                , "expressionNames": $utils.toJson($expNames)
                #end
                #if( !$\{expValues.isEmpty()} )
                , "expressionValues": $utils.toJson($expValues)
                #end
            }
        }`),
      responseMappingTemplate: appsync.MappingTemplate.fromString(
        "$util.toJson($ctx.result)",
      ),
    });

    // updateDocumentStatus — lightweight status-only update (IAM auth, backend only)
    trackingTableDataSource.createResolver("UpdateDocumentStatusResolver", {
      typeName: "Mutation",
      fieldName: "updateDocumentStatus",
      requestMappingTemplate: appsync.MappingTemplate.fromString(`
        #set( $PK = "doc#\${ctx.args.input.ObjectKey}" )
        #set( $expNames = {} )
        #set( $expValues = {} )
        #set( $expSet = {} )
        #foreach( $entry in $ctx.args.input.entrySet() )
            #if( !$util.isNullOrBlank($entry.value) && $entry.key != "ObjectKey" )
                $util.qr( $expSet.put("#\${entry.key}", ":\${entry.key}") )
                $util.qr( $expNames.put("#\${entry.key}", "\${entry.key}") )
                $util.qr( $expValues.put(":\${entry.key}", $util.dynamodb.toDynamoDB($entry.value)) )
            #end
        #end
        #set( $expression = "" )
        #if( !$\{expSet.isEmpty()} )
            #set( $expression = "SET" )
            #foreach( $entry in $expSet.entrySet() )
                #set( $expression = "\${expression} \${entry.key} = \${entry.value}" )
                #if ( $foreach.hasNext )
                    #set( $expression = "\${expression}," )
                #end
            #end
        #end
        {
            "version" : "2018-05-29",
            "operation" : "UpdateItem",
            "key" : {
              "PK": $util.dynamodb.toDynamoDBJson($PK),
              "SK": $util.dynamodb.toDynamoDBJson("none"),
            },
            "update" : {
                "expression": "$expression"
                #if( !$\{expNames.isEmpty()} )
                , "expressionNames": $utils.toJson($expNames)
                #end
                #if( !$\{expValues.isEmpty()} )
                , "expressionValues": $utils.toJson($expValues)
                #end
            }
        }`),
      responseMappingTemplate: appsync.MappingTemplate.fromString(
        "$util.toJson($ctx.result)",
      ),
    });

    // updateDocumentSection — atomic section update within Map operations (IAM auth, backend only)
    trackingTableDataSource.createResolver("UpdateDocumentSectionResolver", {
      typeName: "Mutation",
      fieldName: "updateDocumentSection",
      requestMappingTemplate: appsync.MappingTemplate.fromString(`
        #set( $PK = "doc#\${ctx.args.input.ObjectKey}" )
        #set( $idx = $ctx.args.input.SectionIndex )
        {
            "version" : "2018-05-29",
            "operation" : "UpdateItem",
            "key" : {
              "PK": $util.dynamodb.toDynamoDBJson($PK),
              "SK": $util.dynamodb.toDynamoDBJson("none"),
            },
            "update" : {
                "expression": "SET Sections[$idx] = :section",
                "expressionValues": {
                    ":section": $util.dynamodb.toDynamoDBJson($ctx.args.input.Section)
                }
            }
        }`),
      responseMappingTemplate: appsync.MappingTemplate.fromString(
        "$util.toJson($ctx.result)",
      ),
    });

    trackingTableDataSource.createResolver("GetDocumentResolver", {
      typeName: "Query",
      fieldName: "getDocument",
      requestMappingTemplate: appsync.MappingTemplate.fromString(`
        #set( $PK = "doc#\${context.arguments.ObjectKey}" )
        {
          "version": "2018-05-29",
          "operation": "GetItem",
          "key" : {
            "PK": $util.dynamodb.toDynamoDBJson($PK),
            "SK": $util.dynamodb.toDynamoDBJson("none"),
          }
        }`),
      responseMappingTemplate: appsync.MappingTemplate.fromString(
        "$util.toJson($ctx.result)",
      ),
    });

    // ========================================
    // GSI-based listDocuments and getDocumentCount (replaces VTL Scan)
    // ========================================
    const listDocumentsGSIFunction = new functions.ListDocumentsGSIResolverFunction(
      this,
      "ListDocumentsGSIResolverFunction",
      {
        trackingTable: this._trackingTable,
        usersTable: this._usersTable,
        encryptionKey: this._encryptionKey,
        ...this._vpcConfiguration,
      },
    );

    const listDocumentsGSIDataSource = this.addLambdaDataSource(
      "ListDocumentsGSIDataSource",
      listDocumentsGSIFunction,
      {
        name: "ListDocumentsGSIDataSource",
        description: "Lambda function for GSI-based document listing and counting",
      },
    );

    listDocumentsGSIDataSource.createResolver("ListDocumentResolver", {
      typeName: "Query",
      fieldName: "listDocuments",
    });

    listDocumentsGSIDataSource.createResolver("GetDocumentCountResolver", {
      typeName: "Query",
      fieldName: "getDocumentCount",
    });

    // ========================================
    // listDocumentsByDateRange — separate Lambda resolver
    // ========================================
    const listDocumentsRangeFunction = new functions.ListDocumentsByDateRangeResolverFunction(
      this,
      "ListDocumentsByDateRangeResolverFunction",
      {
        trackingTable: this._trackingTable,
        encryptionKey: this._encryptionKey,
        ...this._vpcConfiguration,
      },
    );

    const listDocumentsRangeDataSource = this.addLambdaDataSource(
      "ListDocumentsByDateRangeDataSource",
      listDocumentsRangeFunction,
      {
        name: "ListDocumentsByDateRangeDataSource",
        description: "Lambda function for listing documents by date range",
      },
    );

    listDocumentsRangeDataSource.createResolver("ListDocumentsByDateRangeResolver", {
      typeName: "Query",
      fieldName: "listDocumentsByDateRange",
    });

    trackingTableDataSource.createResolver("ListDocumentDateHourResolver", {
      typeName: "Query",
      fieldName: "listDocumentsDateHour",
      requestMappingTemplate: appsync.MappingTemplate
        .fromString(`#set( $shardsInDay = 6 )
        #set( $shardDivider = 24 / $shardsInDay )
        #set( $Integer = 0 )
        #set( $now = $util.time.nowISO8601() )
        #set( $hourNow = $Integer.parseInt($now.substring(11, 13)) )
        #set( $date = $util.defaultIfNullOrBlank($ctx.args.date, $now.substring(0, 10)) )
        #set( $hour = $util.defaultIfNull($ctx.args.hour, $hourNow) )
        #if( $hour < 0 || $hour > 23 )
          $util.error("Invalid hour parameter - value should be between 0 and 23")
        #end
        #set( $hourPad = $date.format("%02d", $hour) )
        #set( $hourShard = $hour / $shardDivider )
        #set( $shardPad = $date.format("%02d", $hourShard) )

        #set( $PK = "list#\${date}#s#\${shardPad}" )
        #set( $skPrefix = "ts#\${date}T\${hourPad}" )

        {
          "version" : "2018-05-29",
          "operation" : "Query",
          "query" : {
            "expression": "PK = :PK and begins_with(SK, :prefix)",
            "expressionValues": {
              ":PK": $util.dynamodb.toDynamoDBJson($PK),
              ":prefix": $util.dynamodb.toDynamoDBJson($skPrefix),
            },
          },
        }`),
      responseMappingTemplate: appsync.MappingTemplate.fromString(`{
            "Documents": $util.toJson($ctx.result.items),
            "nextToken": $util.toJson($ctx.result.nextToken)
        }`),
    });

    trackingTableDataSource.createResolver("ListDocumentDateShardResolver", {
      typeName: "Query",
      fieldName: "listDocumentsDateShard",
      requestMappingTemplate: appsync.MappingTemplate
        .fromString(`#set( $shardsInDay = 6 )
        #set( $shardDivider = 24 / $shardsInDay )
        #set( $Integer = 0 )
        #set( $now = $util.time.nowISO8601() )
        #set( $hourNow = $Integer.parseInt($now.substring(11, 13)) )
        #set( $shardNow = $hourNow / $shardDivider )
        #set( $date = $util.defaultIfNullOrBlank($ctx.args.date, $now.substring(0, 10)) )
        #set( $shard = $util.defaultIfNull($ctx.args.shard, $shardNow) )
        #if( $shard >= $shardsInDay )
          $util.error("Invalid shard parameter value - must positive and less than \${shardsInDay}")
        #end
        #set( $hourShard = $hour / $shardDivider )
        #set( $shardPad = $date.format("%02d", $shard) )

        #set( $PK = "list#\${date}#s#\${shardPad}" )

        {
          "version" : "2018-05-29",
          "operation" : "Query",
          "query" : {
            "expression": "PK = :PK",
            "expressionValues": {
              ":PK": $util.dynamodb.toDynamoDBJson($PK),
            }
          }
        }`),
      responseMappingTemplate: appsync.MappingTemplate.fromString(`{
            "Documents": $util.toJson($ctx.result.items),
            "nextToken": $util.toJson($ctx.result.nextToken)
        }`),
    });

    // ========================================
    // Subscription resolvers (None data source)
    // ========================================
    const subscriptionDataSource = this.addNoneDataSource(
      "SubscriptionNoneDataSource",
      {
        name: "SubscriptionNoneDataSource",
        description: "None data source for subscription resolvers",
      },
    );

    subscriptionDataSource.createResolver("OnCreateDocumentResolver", {
      typeName: "Subscription",
      fieldName: "onCreateDocument",
      requestMappingTemplate: appsync.MappingTemplate.fromString(`
        {
          "version": "2018-05-29",
          "payload": {}
        }`),
      responseMappingTemplate: appsync.MappingTemplate.fromString(
        "$util.toJson($context.result)",
      ),
    });

    subscriptionDataSource.createResolver("OnUpdateDocumentResolver", {
      typeName: "Subscription",
      fieldName: "onUpdateDocument",
      requestMappingTemplate: appsync.MappingTemplate.fromString(`
        {
          "version": "2018-05-29",
          "payload": {}
        }`),
      responseMappingTemplate: appsync.MappingTemplate.fromString(
        "$util.toJson($context.result)",
      ),
    });
  }

  /**
   * Add Get File Contents Data Source to the GraphQL API.
   *
   * This method creates a Lambda data source for retrieving file contents from S3 buckets.
   * The data source can be used to create resolvers that allow clients to fetch
   * document contents from various S3 buckets (input, output, configuration).
   *
   * @param inputBucket The S3 bucket for input documents
   * @param outputBucket The S3 bucket for output documents
   * @param configurationBucket The S3 bucket for configuration files
   * @param encryptionKey The KMS key for encryption
   * @param vpcConfiguration The VPC configuration
   * @returns The created Lambda data source
   */
  private addGetFileContentsDataSource(
    inputBucket: IBucket,
    outputBucket: IBucket,
    encryptionKey?: kms.IKey,
    vpcConfiguration?: VpcConfiguration,
  ): appsync.LambdaDataSource {
    const getFileContentsResolverFunction =
      new functions.GetFileContentsResolverFunction(
        this,
        "GetFileContentsResolverFunction",
        {
          inputBucket: inputBucket,
          outputBucket: outputBucket,
          encryptionKey: encryptionKey,
          logGroup: new logs.LogGroup(this, "GetFileContentsResolverLogGroup", {
            encryptionKey: encryptionKey,
            retention: logs.RetentionDays.ONE_WEEK,
          }),
          ...vpcConfiguration,
        },
      );

    return this.addLambdaDataSource(
      "GetFileContentsDataSource",
      getFileContentsResolverFunction,
      {
        name: "GetFileContentsResolver",
        description: "Get the contents of a file from S3",
      },
    );
  }

  /**
   * Create Get File Contents Query Resolver using the provided data source.
   *
   * This method creates a resolver that handles file content retrieval queries
   * using the specified Lambda data source.
   *
   * @param dataSource The Lambda data source for file content retrieval
   * @returns The created resolver
   */
  private createGetFileContentsQueryResolver(
    dataSource: appsync.LambdaDataSource,
  ): appsync.Resolver {
    return this.createResolver("GetFileContentsResolver", {
      dataSource: dataSource,
      typeName: "Query",
      fieldName: "getFileContents",
    });
  }

  /**
   * Add Configuration Resolver for getting and updating configuration.
   *
   * This method adds resolvers to the GraphQL API for querying and updating
   * configuration settings stored in the provided configuration table.
   *
   * @param configurationTable The DynamoDB table for configuration storage
   * @param encryptionKey The KMS key for encryption
   * @param logRetention The log retention period
   * @param vpcConfiguration The VPC configuration
   */
  private addConfigurationResolver(
    configurationTable: IConfigurationTable,
    encryptionKey?: kms.IKey,
    logRetention?: logs.RetentionDays,
    vpcConfiguration?: VpcConfiguration,
  ): void {
    const configurationResolverFunction =
      new functions.ConfigurationResolverFunction(
        this,
        "ConfigurationResolverFunction",
        {
          configurationTable: configurationTable,
          encryptionKey: encryptionKey,
          logGroup: new logs.LogGroup(
            this,
            "ConfigurationResolverFunctionLogGroup",
            {
              encryptionKey: encryptionKey,
              retention: logRetention || logs.RetentionDays.ONE_WEEK,
            },
          ),
          ...vpcConfiguration,
        },
      );

    // Create AppSync data source
    const configurationDataSource = this.addLambdaDataSource(
      "ConfigurationDataSource",
      configurationResolverFunction,
      {
        name: "ConfigurationDataSource",
        description: "Lambda function to manage configuration via GraphQL API",
      },
    );

    // Create resolvers for configuration queries
    this.createResolver("GetConfigVersionsResolver", {
      dataSource: configurationDataSource,
      typeName: "Query",
      fieldName: "getConfigVersions",
    });

    this.createResolver("GetConfigVersionResolver", {
      dataSource: configurationDataSource,
      typeName: "Query",
      fieldName: "getConfigVersion",
    });

    this.createResolver("GetPricingResolver", {
      dataSource: configurationDataSource,
      typeName: "Query",
      fieldName: "getPricing",
    });

    this.createResolver("ListConfigurationLibraryResolver", {
      dataSource: configurationDataSource,
      typeName: "Query",
      fieldName: "listConfigurationLibrary",
    });

    this.createResolver("GetConfigurationLibraryFileResolver", {
      dataSource: configurationDataSource,
      typeName: "Query",
      fieldName: "getConfigurationLibraryFile",
    });

    // Create resolvers for configuration mutations
    this.createResolver("UpdateConfigurationResolver", {
      dataSource: configurationDataSource,
      typeName: "Mutation",
      fieldName: "updateConfiguration",
    });

    this.createResolver("SetActiveVersionResolver", {
      dataSource: configurationDataSource,
      typeName: "Mutation",
      fieldName: "setActiveVersion",
    });

    this.createResolver("DeleteConfigVersionResolver", {
      dataSource: configurationDataSource,
      typeName: "Mutation",
      fieldName: "deleteConfigVersion",
    });

    this.createResolver("UpdatePricingResolver", {
      dataSource: configurationDataSource,
      typeName: "Mutation",
      fieldName: "updatePricing",
    });

    this.createResolver("RestoreDefaultPricingResolver", {
      dataSource: configurationDataSource,
      typeName: "Mutation",
      fieldName: "restoreDefaultPricing",
    });
  }

  /**
   * Add Delete Document Data Source to the GraphQL API.
   *
   * This method creates a Lambda data source for document deletion operations.
   * The data source can be used to create resolvers that allow clients to delete
   * documents from both the tracking table and the S3 buckets.
   *
   * @param trackingTable The DynamoDB table for tracking documents
   * @param inputBucket The S3 bucket for input documents
   * @param outputBucket The S3 bucket for output documents
   * @param encryptionKey The KMS key for encryption
   * @param logRetention The log retention period
   * @param vpcConfiguration The VPC configuration
   * @returns The created Lambda data source
   */
  private addDeleteDocumentDataSource(
    trackingTable: ITrackingTable,
    inputBucket: IBucket,
    outputBucket: IBucket,
    encryptionKey?: kms.IKey,
    logRetention?: logs.RetentionDays,
    vpcConfiguration?: VpcConfiguration,
  ): appsync.LambdaDataSource {
    const deleteDocumentResolverFunction =
      new functions.DeleteDocumentResolverFunction(
        this,
        "DeleteDocumentResolverFunction",
        {
          trackingTable: trackingTable,
          inputBucket: inputBucket,
          outputBucket: outputBucket,
          encryptionKey: encryptionKey,
          logGroup: new logs.LogGroup(
            this,
            "DeleteDocumentResolverFunctionLogGroup",
            {
              encryptionKey: encryptionKey,
              retention: logRetention || logs.RetentionDays.ONE_WEEK,
            },
          ),
          ...vpcConfiguration,
        },
      );

    // Create and return AppSync data source
    return this.addLambdaDataSource(
      "DeleteDocumentDataSource",
      deleteDocumentResolverFunction,
      {
        name: "DeleteDocumentDataSource",
        description: "Lambda function for deleting documents",
      },
    );
  }

  /**
   * Create Delete Document Mutation Resolver using the provided data source.
   *
   * This method creates a resolver that handles document deletion mutations
   * using the specified Lambda data source.
   *
   * @param dataSource The Lambda data source for document deletion
   * @returns The created resolver
   */
  private createDeleteDocumentMutationResolver(
    dataSource: appsync.LambdaDataSource,
  ): appsync.Resolver {
    return this.createResolver("DeleteDocumentResolver", {
      dataSource: dataSource,
      typeName: "Mutation",
      fieldName: "deleteDocument",
    });
  }

  /**
   * Add Reprocess Document Data Source to the GraphQL API.
   *
   * This method creates a Lambda data source for document reprocessing operations.
   * The data source can be used to create resolvers that allow clients to trigger
   * reprocessing of documents that have already been processed.
   *
   * @param inputBucket The S3 bucket for input documents
   * @param encryptionKey The KMS key for encryption
   * @param logRetention The log retention period
   * @param vpcConfiguration The VPC configuration
   * @returns The created Lambda data source
   */
  private addReprocessDocumentDataSource(
    inputBucket: IBucket,
    encryptionKey?: kms.IKey,
    logRetention?: logs.RetentionDays,
    vpcConfiguration?: VpcConfiguration,
  ): appsync.LambdaDataSource {
    const reprocessDocumentResolverFunction =
      new functions.ReprocessDocumentResolverFunction(
        this,
        "ReprocessDocumentResolverFunction",
        {
          inputBucket: inputBucket,
          encryptionKey: encryptionKey,
          logGroup: new logs.LogGroup(
            this,
            "ReprocessDocumentResolverFunctionLogGroup",
            {
              encryptionKey: encryptionKey,
              retention: logRetention || logs.RetentionDays.ONE_WEEK,
            },
          ),
          ...vpcConfiguration,
        },
      );

    return this.addLambdaDataSource(
      "ReprocessDocumentDataSource",
      reprocessDocumentResolverFunction,
      {
        name: "ReprocessDocumentDataSource",
        description: "Lambda function for reprocessing documents",
      },
    );
  }

  /**
   * Create Reprocess Document Mutation Resolver using the provided data source.
   *
   * This method creates a resolver that handles document reprocessing mutations
   * using the specified Lambda data source.
   *
   * @param dataSource The Lambda data source for document reprocessing
   * @returns The created resolver
   */
  private createReprocessDocumentMutationResolver(
    dataSource: appsync.LambdaDataSource,
  ): appsync.Resolver {
    return this.createResolver("ReprocessDocumentResolver", {
      dataSource: dataSource,
      typeName: "Mutation",
      fieldName: "reprocessDocument",
    });
  }

  /**
   * Add Upload Document Data Source to the GraphQL API.
   *
   * This method creates a Lambda data source for generating presigned URLs
   * for uploading documents directly to S3 from the client.
   *
   * @param inputBucket The S3 bucket for input documents
   * @param outputBucket The S3 bucket for output documents
   * @param encryptionKey The KMS key for encryption
   * @param logRetention The log retention period
   * @param vpcConfiguration The VPC configuration
   * @returns The created Lambda data source
   */
  private addUploadDocumentDataSource(
    inputBucket: IBucket,
    outputBucket: IBucket,
    encryptionKey?: kms.IKey,
    logRetention?: logs.RetentionDays,
    vpcConfiguration?: VpcConfiguration,
  ): {
    dataSource: appsync.LambdaDataSource;
    resolverFunction: lambda.IFunction;
  } {
    const uploadResolverFunction = new functions.UploadResolverFunction(
      this,
      "UploadResolverFunction",
      {
        inputBucket: inputBucket,
        outputBucket: outputBucket,
        encryptionKey: encryptionKey,
        logGroup: new logs.LogGroup(this, "UploadResolverFunctionLogGroup", {
          encryptionKey: encryptionKey,
          retention: logRetention || logs.RetentionDays.ONE_WEEK,
        }),
        ...vpcConfiguration,
      },
    );

    const dataSource = this.addLambdaDataSource(
      "UploadResolverDataSource",
      uploadResolverFunction,
      {
        name: "UploadResolverDataSource",
        description: "Lambda function for generating presigned URLs",
      },
    );

    return { dataSource, resolverFunction: uploadResolverFunction };
  }

  /**
   * Create Upload Document Mutation Resolver using the provided data source.
   *
   * This method creates a resolver that handles document upload mutations
   * using the specified Lambda data source.
   *
   * @param dataSource The Lambda data source for document uploads
   * @returns The created resolver
   */
  private createUploadDocumentMutationResolver(
    dataSource: appsync.LambdaDataSource,
  ): appsync.Resolver {
    return this.createResolver("UploadDocumentResolver", {
      dataSource: dataSource,
      typeName: "Mutation",
      fieldName: "uploadDocument",
    });
  }
}
