version = 0.1

[default.deploy.parameters]
stack_name = "customPromptGeneratorLambda"
resolve_s3 = true
s3_prefix = "customPromptGeneratorLambda"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "PermissionsBoundaryArn=\"\""
image_repositories = []
